import type { AppItem, LegalPage } from "@/lib/types";

const subscriptionTerms = (appName: string, email: string, updatedAt: string): LegalPage => ({
  title: `Condiciones de suscripción de ${appName}`,
  updatedAt,
  body: [
    "## 1. Alcance",
    `Estas condiciones complementan los Términos de uso y la Política de privacidad de ${appName}. La versión gratuita puede utilizarse sin contratar una suscripción.`,
    "## 2. Compra y facturación",
    "Las suscripciones y compras se procesan mediante Apple In-App Purchase. Apple muestra el precio final, impuestos, moneda, duración y cualquier oferta disponible antes de confirmar. El desarrollador no recibe los datos completos de tu tarjeta.",
    "## 3. Renovación automática",
    "Las suscripciones se renuevan automáticamente salvo cancelación, normalmente con cargo durante las 24 horas anteriores al final del periodo. Puedes gestionarlas en Ajustes del dispositivo > tu nombre > Suscripciones. Eliminar la app no cancela la suscripción.",
    "## 4. Pruebas y ofertas",
    "La elegibilidad, duración y precio posterior de una prueba u oferta introductoria son los que Apple muestra en el momento de compra. Si no cancelas antes de finalizar, se inicia el periodo de pago indicado.",
    "## 5. Cambios de precio",
    "Los precios pueden variar por territorio. Apple comunicará los cambios y solicitará consentimiento cuando la normativa o sus reglas lo exijan.",
    "## 6. Restauración, cancelación y acceso",
    `Puedes restaurar compras realizadas con el mismo Apple ID desde ${appName}. Al terminar el periodo pagado pierdes las funciones Pro, pero tus datos no se eliminan automáticamente.`,
    "## 7. Reembolsos",
    "Apple gestiona los reembolsos. Puedes solicitarlos en reportaproblem.apple.com; el desarrollador no puede emitir directamente reembolsos de pagos procesados por Apple.",
    "## 8. Contacto",
    `Responsable: Lester Romero Bernardo (RomeroDev), Valencia, España. Soporte: ${email}.`
  ]
});

const repsPrivacy: LegalPage = {
  title: "Política de privacidad de StreakRep",
  title_en: "Privacy Policy of StreakRep",
  updatedAt: "2026-07-11",
  body: [
    "Esta política explica cómo StreakRep trata la información cuando utilizas la aplicación móvil, sus widgets, la aplicación para Apple Watch y las funciones sociales.",
    "## 1. Qué datos puede tratar StreakRep",
    "Dependiendo de las funciones que actives, StreakRep puede tratar:",
    "- **Cuenta y perfil:** nombre, alias, correo electrónico si lo proporcionas, idioma, unidades, preferencias de entrenamiento y configuración de la aplicación.",
    "- **Entrenamiento:** planes, ejercicios, series, repeticiones, cargas, duración, notas, objetivos, historial, sesiones programadas y progresos.",
    "- **Salud y forma física:** datos que autorizas a leer o escribir mediante Apple Health/HealthKit, como peso, altura, pasos, energía, hidratación, sueño, frecuencia cardíaca y entrenamientos. Estos datos solo se solicitan cuando la función correspondiente lo necesita.",
    "- **Ubicación:** puntos de ruta y datos de localización durante actividades exteriores, únicamente si autorizas la ubicación y comienzas una actividad que la requiere.",
    "- **Fotos y audio:** fotos de progreso y notas de voz cuando utilizas esas funciones.",
    "- **Funciones sociales:** nombre de usuario, biografía, ubicación que decidas publicar, publicaciones, comentarios, reacciones, seguimientos, retos, reportes y bloqueos.",
    "- **Compras:** estado de suscripción y derechos de acceso a funciones Pro. El pago se procesa mediante Apple y la gestión técnica de suscripciones puede utilizar RevenueCat.",
    "- **Diagnóstico y uso:** eventos técnicos, errores, rendimiento y uso agregado de funciones para mantener y mejorar StreakRep. No utilizamos datos de HealthKit para publicidad ni para crear perfiles publicitarios.",
    "No necesitas activar HealthKit, ubicación, cámara, micrófono, fotos o funciones sociales para utilizar las funciones básicas de registro de entrenamientos.",
    "## 2. Cómo usamos los datos",
    "Usamos los datos para:",
    "1. proporcionar el registro de entrenamientos, planes, objetivos y progreso;",
    "2. mostrar métricas y recomendaciones dentro de StreakRep;",
    "3. sincronizar widgets, Apple Watch y funciones de continuidad;",
    "4. guardar o restaurar tus datos cuando eliges exportar o importar una copia;",
    "5. prestar las funciones sociales que actives;",
    "6. procesar compras, restauraciones y acceso Pro;",
    "7. detectar errores, prevenir abuso, proteger la comunidad y mejorar la estabilidad;",
    "8. cumplir obligaciones legales y responder a solicitudes de soporte.",
    "## 3. Apple Health y datos sensibles",
    "HealthKit es un repositorio controlado por Apple. StreakRep solo accede a las categorías para las que concedes permiso y puedes revocar ese permiso en **Ajustes > Salud > Acceso a datos y dispositivos > StreakRep**.",
    "StreakRep no vende datos de salud, no los utiliza para publicidad y no los comparte con anunciantes ni corredores de datos. Las métricas de salud se utilizan para ofrecer funciones de entrenamiento, recuperación y progreso dentro de la aplicación.",
    "El backup automático de iCloud contiene únicamente una proyección operativa de los datos: planes, rutinas, ejercicios, preferencias y registros de entrenamiento sin métricas sanitarias, rutas, fotos ni datos derivados de HealthKit. Las exportaciones manuales JSON/CSV pueden contener más información y solo se crean cuando tú las solicitas.",
    "## 4. Dónde se almacenan y con quién se comparten",
    "StreakRep puede utilizar los siguientes proveedores tecnológicos:",
    "- **Apple / iCloud / CloudKit:** sincronización operativa, funciones sociales y almacenamiento de la cuenta iCloud según las capacidades activadas.",
    "- **Apple HealthKit:** lectura o escritura de datos de salud con tu autorización.",
    "- **Apple StoreKit:** compras y suscripciones dentro de la App Store.",
    "- **RevenueCat:** gestión técnica de derechos y estado de suscripción; no procesa el contenido de tus datos de salud para publicidad.",
    "- **Firebase Analytics y Crashlytics:** métricas técnicas, errores y uso agregado, sujetas a la configuración y documentación de Apple/Firebase.",
    "No cedemos datos personales a terceros para que los vendan o los utilicen para publicidad basada en salud. Podemos revelar información cuando sea necesario para cumplir la ley, proteger derechos o investigar fraude y abuso.",
    "## 5. Funciones sociales y contenido público",
    "Si activas la comunidad, la información que publiques puede ser visible para otros usuarios. No publiques datos médicos, credenciales, direcciones exactas ni información que no quieras hacer pública.",
    "Puedes reportar contenido y bloquear usuarios desde la aplicación. StreakRep puede conservar reportes, bloqueos y registros técnicos necesarios para investigar abuso y aplicar las normas de la comunidad.",
    "La comunidad está destinada a personas de **13 años o más**. Si detectamos que una persona menor de 13 años ha activado funciones sociales, podremos desactivarlas y eliminar el contenido asociado cuando proceda.",
    "## 6. Conservación y eliminación",
    "Conservamos los datos mientras mantengas una cuenta o mientras sean necesarios para prestar el servicio, resolver disputas, cumplir obligaciones legales o proteger la seguridad. Puedes eliminar los datos locales desde la aplicación y solicitar la eliminación de datos asociados a servicios remotos escribiendo a romerodev.app+streakreps@gmail.com.",
    "Las copias exportadas que guardes en iCloud Drive, Archivos, copias de seguridad del dispositivo u otros servicios quedan bajo tu control y debes eliminarlas desde esos servicios si quieres retirarlas.",
    "## 7. Tus derechos",
    "Según tu lugar de residencia, puedes solicitar acceso, rectificación, eliminación, limitación, oposición, portabilidad o retirada del consentimiento. También puedes reclamar ante la autoridad de protección de datos competente. Para ejercer derechos, escribe a romerodev.app+streakreps@gmail.com indicando el correo o identificador asociado a la solicitud.",
    "## 8. Seguridad",
    "Aplicamos controles razonables de acceso, minimización y protección del almacenamiento. Ningún sistema conectado a Internet es completamente seguro. Debes mantener protegidos tu dispositivo, Apple ID y archivos exportados.",
    "## 9. Cambios en esta política",
    "Podemos actualizar esta política para reflejar cambios legales, técnicos o funcionales. Publicaremos la nueva versión en esta URL e indicaremos la fecha de actualización.",
    "## 10. Contacto",
    "Para preguntas de privacidad, solicitudes de derechos o reportes relacionados con datos personales:",
    "**RomeroDev**",
    "**Calle Madre Juana María Condesa Lluch 6, Valencia**",
    "**romerodev.app+streakreps@gmail.com**"
  ],
  body_en: [
    "This policy explains how StreakRep processes information when you use the mobile application, its widgets, the Apple Watch application, and social features.",
    "## 1. What data StreakRep may process",
    "Depending on the features you activate, StreakRep may process:",
    "- **Account and profile:** name, alias, email address if provided, language, units, training settings, and application configuration.",
    "- **Workouts:** plans, exercises, sets, repetitions, weights, duration, notes, goals, history, scheduled sessions, and progress.",
    "- **Health and fitness:** data you authorize to read or write via Apple Health/HealthKit, such as weight, height, steps, energy, hydration, sleep, heart rate, and workouts. This data is only requested when the corresponding feature needs it.",
    "- **Location:** route points and location data during outdoor activities, only if you authorize location access and start an activity that requires it.",
    "- **Photos and audio:** progress photos and voice notes when you use those features.",
    "- **Social features:** username, bio, location you choose to publish, posts, comments, reactions, follows, challenges, reports, and blocks.",
    "- **Purchases:** subscription status and Pro feature access rights. Payment is processed by Apple, and the technical management of subscriptions may use RevenueCat.",
    "- **Diagnostics and usage:** technical events, errors, performance, and aggregate feature usage to maintain and improve StreakRep. We do not use HealthKit data for advertising or to build advertising profiles.",
    "You do not need to activate HealthKit, location, camera, microphone, photos, or social features to use the basic workout logging features.",
    "## 2. How we use the data",
    "We use the data to:",
    "1. provide workout logging, plans, goals, and progress tracking;",
    "2. display metrics and recommendations within StreakRep;",
    "3. sync widgets, Apple Watch, and continuity features;",
    "4. save or restore your data when you choose to export or import a copy;",
    "5. provide the social features you activate;",
    "6. process purchases, restorations, and Pro access;",
    "7. detect errors, prevent abuse, protect the community, and improve stability;",
    "8. comply with legal obligations and respond to support requests.",
    "## 3. Apple Health and sensitive data",
    "HealthKit is a repository controlled by Apple. StreakRep only accesses the categories for which you grant permission, and you can revoke that permission at **Settings > Health > Data Access & Devices > StreakRep**.",
    "StreakRep does not sell health data, does not use it for advertising, and does not share it with advertisers or data brokers. Health metrics are used to offer training, recovery, and progress features within the application.",
    "iCloud automatic backup contains only an operational projection of the data: plans, routines, exercises, preferences, and workout logs without health metrics, routes, photos, or data derived from HealthKit. Manual JSON/CSV exports may contain more information and are only created when you request them.",
    "## 4. Where data is stored and with whom it is shared",
    "StreakRep may use the following technology providers:",
    "- **Apple / iCloud / CloudKit:** operational synchronization, social features, and iCloud account storage depending on the active capabilities.",
    "- **Apple HealthKit:** reading or writing health data with your authorization.",
    "- **Apple StoreKit:** in-app purchases and subscriptions within the App Store.",
    "- **RevenueCat:** technical management of rights and subscription status; does not process your health data content for advertising.",
    "- **Firebase Analytics and Crashlytics:** technical metrics, errors, and aggregated usage, subject to Apple/Firebase settings and documentation.",
    "We do not transfer personal data to third parties for sale or use for health-based advertising. We may disclose information when necessary to comply with the law, protect rights, or investigate fraud and abuse.",
    "## 5. Social features and public content",
    "If you activate the community, the information you post may be visible to other users. Do not post medical data, credentials, exact addresses, or information you do not want to make public.",
    "You can report content and block users from the application. StreakRep may retain reports, blocks, and technical logs necessary to investigate abuse and enforce community standards.",
    "The community is intended for people aged **13 or older**. If we detect that a person under 13 has activated social features, we may deactivate them and delete the associated content where appropriate.",
    "## 6. Retention and deletion",
    "We retain data for as long as you maintain an account or as long as necessary to provide the service, resolve disputes, comply with legal obligations, or protect security. You can delete local data from the application and request the deletion of data associated with remote services by writing to romerodev.app+streakreps@gmail.com.",
    "Exported copies you save to iCloud Drive, Files, device backups, or other services remain under your control, and you must delete them from those services if you want to remove them.",
    "## 7. Your rights",
    "Depending on your place of residence, you may request access, rectification, deletion, restriction, opposition, portability, or withdrawal of consent. You can also lodge a complaint with the competent data protection authority. To exercise your rights, write to romerodev.app+streakreps@gmail.com indicating the email or identifier associated with the request.",
    "## 8. Security",
    "We apply reasonable access, minimization, and storage protection controls. No system connected to the Internet is completely secure. You must keep your device, Apple ID, and exported files protected.",
    "## 9. Changes to this policy",
    "We may update this policy to reflect legal, technical, or functional changes. We will publish the new version on this URL and indicate the update date.",
    "## 10. Contact",
    "For privacy questions, rights requests, or reports related to personal data:",
    "**RomeroDev**",
    "**Calle Madre Juana María Condesa Lluch 6, Valencia**",
    "**romerodev.app+streakreps@gmail.com**"
  ]
};

const repsTerms: LegalPage = {
  title: "Términos de uso de StreakRep",
  title_en: "Terms of Use of StreakRep",
  updatedAt: "2026-07-11",
  body: [
    "Estos términos regulan el uso de StreakRep, sus funciones de entrenamiento, Apple Watch, widgets, exportaciones y comunidad.",
    "## 1. Aceptación",
    "Al instalar, acceder o utilizar StreakRep aceptas estos términos y la Política de privacidad. Si no los aceptas, no utilices la aplicación.",
    "## 2. Naturaleza del servicio",
    "StreakRep es una herramienta de registro, planificación y seguimiento de actividad física. No es un servicio médico, no diagnostica enfermedades y no sustituye el consejo de un médico, fisioterapeuta, nutricionista u otro profesional cualificado.",
    "Consulta con un profesional antes de iniciar o modificar un programa de ejercicio, especialmente si tienes una lesión, enfermedad, embarazo, síntomas o cualquier condición que pueda afectar a la actividad física. Detén la actividad y busca ayuda si notas dolor intenso, mareo, falta de aire u otros síntomas preocupantes.",
    "## 3. Cuenta y uso responsable",
    "Debes proporcionar información razonablemente exacta y proteger el acceso a tu dispositivo, Apple ID y cuenta. Eres responsable de la actividad realizada desde tus dispositivos.",
    "No debes:",
    "- utilizar StreakRep para actividades ilegales o peligrosas;",
    "- cargar malware, automatizar abusos o intentar acceder a sistemas ajenos;",
    "- suplantar a otra persona;",
    "- publicar datos personales de terceros sin autorización;",
    "- utilizar la comunidad para acoso, amenazas, spam, fraude o contenido sexual dirigido a menores;",
    "- manipular reportes, reacciones, seguidores, retos o métricas;",
    "- extraer, copiar o redistribuir de forma sistemática el catálogo o contenido de StreakRep.",
    "## 4. Comunidad y contenido generado por usuarios",
    "Conservas la titularidad del contenido que publiques. Al publicarlo, concedes a StreakRep una licencia limitada, mundial y no exclusiva para alojarlo, mostrarlo, distribuirlo dentro del servicio y crear copias técnicas necesarias para operar la comunidad.",
    "Garantizas que tienes derechos sobre el contenido y que no infringe leyes ni derechos de terceros. Podemos ocultar, retirar o limitar contenido que infrinja estos términos, sea reportado de forma creíble o genere riesgos de seguridad. Puedes reportar publicaciones y comentarios desde la aplicación.",
    "## 5. Salud, permisos y dispositivo",
    "Las funciones HealthKit, ubicación, cámara, micrófono, fotos, notificaciones, Apple Watch y Apple Music dependen de permisos del sistema. Puedes concederlos, rechazarlos o revocarlos desde Ajustes. Algunas funciones dejarán de estar disponibles si revocas un permiso.",
    "StreakRep no garantiza que los datos capturados por sensores, GPS, Apple Watch o HealthKit sean completos, exactos o continuos. Las métricas son orientativas.",
    "## 6. Propiedad intelectual",
    "StreakRep, su marca, diseño, software, textos, catálogo, gráficos y materiales propios pertenecen a RomeroDev o a sus licenciantes. Estos términos no te transfieren derechos de propiedad intelectual. Solo recibes una licencia personal, limitada, revocable y no transferible para utilizar la aplicación conforme a estos términos.",
    "## 7. Disponibilidad y cambios",
    "Podemos actualizar, modificar, limitar o retirar funciones. Intentaremos mantener la continuidad razonable del servicio, pero no garantizamos disponibilidad ininterrumpida, compatibilidad con todos los dispositivos ni conservación indefinida de datos.",
    "Las exportaciones manuales son responsabilidad del usuario. Debes conservar las copias que necesites.",
    "## 8. Suspensión y cancelación",
    "Podemos suspender o cancelar el acceso cuando exista incumplimiento, fraude, abuso, riesgo para otros usuarios o exigencia legal. Puedes dejar de usar StreakRep en cualquier momento. La eliminación de la aplicación no cancela automáticamente una suscripción de Apple.",
    "## 9. Limitación de responsabilidad",
    "En la medida permitida por la ley, StreakRep se proporciona “tal cual”. No seremos responsables de lesiones, decisiones de entrenamiento, pérdida de datos por falta de exportación, interrupciones de servicios de Apple o terceros, ni daños indirectos, salvo cuando la ley establezca lo contrario o exista dolo o negligencia no limitable.",
    "Nada de estos términos limita derechos irrenunciables del consumidor.",
    "## 10. Servicios de Apple",
    "Si descargas StreakRep desde la App Store, Apple es un tercero beneficiario de estos términos y puede hacerlos cumplir frente a ti conforme a las reglas aplicables de la App Store. Apple no está obligado a prestar soporte de mantenimiento para StreakRep.",
    "## 11. Ley aplicable y contacto",
    "Estos términos se regirán por las leyes de **España, Comunidad Valenciana**, sin perjuicio de los derechos imperativos del consumidor. Las controversias se someterán a los tribunales legalmente competentes.",
    "Contacto: **romerodev.app+streakreps@gmail.com**",
    "Entidad: **RomeroDev**",
    "Dirección: **Calle Madre Juana María Condesa Lluch 6, Valencia**"
  ],
  body_en: [
    "These terms govern the use of StreakRep, its workout features, Apple Watch, widgets, exports, and community.",
    "## 1. Acceptance",
    "By installing, accessing, or using StreakRep, you accept these terms and the Privacy Policy. If you do not accept them, do not use the application.",
    "## 2. Nature of the service",
    "StreakRep is a tool for logging, planning, and tracking physical activity. It is not a medical service, does not diagnose diseases, and does not replace the advice of a physician, physical therapist, nutritionist, or other qualified professional.",
    "Consult with a professional before starting or modifying an exercise program, especially if you have an injury, illness, pregnancy, symptoms, or any condition that may affect physical activity. Stop the activity and seek help if you notice intense pain, dizziness, shortness of breath, or other worrying symptoms.",
    "## 3. Account and responsible use",
    "You must provide reasonably accurate information and protect access to your device, Apple ID, and account. You are responsible for the activity carried out from your devices.",
    "You must not:",
    "- use StreakRep for illegal or dangerous activities;",
    "- upload malware, automate abuse, or attempt to access third-party systems;",
    "- impersonate another person;",
    "- publish personal data of third parties without authorization;",
    "- use the community for harassment, threats, spam, fraud, or sexual content directed at minors;",
    "- manipulate reports, reactions, followers, challenges, or metrics;",
    "- systematically extract, copy, or redistribute the catalog or content of StreakRep.",
    "## 4. Community and user-generated content",
    "You retain ownership of the content you publish. By publishing it, you grant StreakRep a limited, worldwide, non-exclusive license to host, display, distribute it within the service, and create technical copies necessary to operate the community.",
    "You warrant that you have rights to the content and that it does not infringe laws or third-party rights. We may hide, remove, or limit content that infringes these terms, is credibly reported, or creates security risks. You can report posts and comments from the application.",
    "## 5. Health, permissions, and device",
    "HealthKit, location, camera, microphone, photos, notifications, Apple Watch, and Apple Music features depend on system permissions. You can grant, reject, or revoke them from Settings. Some features will cease to be available if you revoke a permission.",
    "StreakRep does not guarantee that the data captured by sensors, GPS, Apple Watch, or HealthKit is complete, accurate, or continuous. Metrics are orientative.",
    "## 6. Intellectual property",
    "StreakRep, its brand, design, software, texts, catalog, graphics, and own materials belong to RomeroDev or its licensors. These terms do not transfer intellectual property rights to you. You only receive a personal, limited, revocable, and non-transferable license to use the application in accordance with these terms.",
    "## 7. Availability and changes",
    "we may update, modify, limit, or withdraw features. We will try to maintain reasonable service continuity, but we do not guarantee uninterrupted availability, compatibility with all devices, or indefinite preservation of data.",
    "Manual exports are the responsibility of the user. You must keep the copies you need.",
    "## 8. Suspension and termination",
    "We may suspend or terminate access when there is non-compliance, fraud, abuse, risk to other users, or legal requirements. You can stop using StreakRep at any time. Removing the application does not automatically cancel an Apple subscription.",
    "## 9. Limitation of liability",
    "To the extent permitted by law, StreakRep is provided \"as is\". We will not be liable for injuries, training decisions, data loss due to lack of export, interruptions of Apple or third-party services, or indirect damages, except when the law establishes otherwise or there is non-limitable willful intent or negligence.",
    "Nothing in these terms limits the non-waivable rights of the consumer.",
    "## 10. Apple Services",
    "If you download StreakRep from the App Store, Apple is a third-party beneficiary of these terms and may enforce them against you in accordance with the applicable rules of the App Store. Apple is not obligated to provide maintenance support for StreakRep.",
    "## 11. Applicable law and contact",
    "These terms shall be governed by the laws of **Spain, Comunidad Valenciana**, without prejudice to the mandatory rights of the consumer. Disputes shall be submitted to the legally competent courts.",
    "Contact: **romerodev.app+streakreps@gmail.com**",
    "Entity: **RomeroDev**",
    "Address: **Calle Madre Juana María Condesa Lluch 6, Valencia**"
  ]
};

const repsSubscriptions: LegalPage = {
  title: "Condiciones de suscripción Pro de StreakRep",
  title_en: "Pro Subscription Conditions of StreakRep",
  updatedAt: "2026-07-11",
  body: [
    "Estas condiciones complementan los Términos de uso y la Política de privacidad.",
    "## 1. Qué es Pro",
    "StreakRep Pro desbloquea funciones premium que pueden incluir analítica avanzada, progresión configurable, tarjetas para compartir, funciones avanzadas de Apple Watch, backups operativos de iCloud y otras prestaciones que se indiquen en la pantalla de compra.",
    "La disponibilidad exacta puede variar por versión, país, dispositivo y configuración de la oferta mostrada en Apple.",
    "## 2. Compra y proveedor de pago",
    "Las suscripciones se ofrecen mediante Apple In-App Purchase/StoreKit. Apple gestiona el cobro, los impuestos aplicables y la relación de facturación. StreakRep no recibe ni almacena los datos completos de tu tarjeta.",
    "La pantalla de compra mostrará antes de confirmar el precio, duración, renovación y condiciones de cualquier prueba gratuita u oferta introductoria aplicable.",
    "## 3. Renovación automática",
    "Salvo que canceles, la suscripción se renovará automáticamente al final del periodo contratado. El pago se cargará a tu Apple ID normalmente dentro de las 24 horas anteriores al final del periodo vigente.",
    "Puedes cancelar o modificar la suscripción en:",
    "**Ajustes del iPhone/iPad → tu nombre → Suscripciones → StreakRep**",
    "Cancelar la aplicación o eliminarla del dispositivo no cancela la renovación.",
    "## 4. Pruebas gratuitas y ofertas",
    "Si se ofrece una prueba gratuita, cualquier condición, duración y precio posterior se mostrará en la pantalla de compra. Si no cancelas antes de que termine, comenzará la suscripción de pago correspondiente.",
    "Una persona puede no tener derecho a una prueba u oferta si ya la utilizó o si Apple determina que no cumple los requisitos.",
    "## 5. Cambios de precio",
    "Apple puede aplicar cambios de precio conforme a sus reglas y procesos de notificación. Si un cambio requiere tu consentimiento, Apple te informará y podrá solicitarlo antes de renovar.",
    "No se realiza ningún cambio de precio por el mero hecho de actualizar StreakRep. Las condiciones que aplican son las que aparecen en Apple para tu territorio y en el momento de la compra.",
    "## 6. Restaurar compras y acceso",
    "Puedes utilizar **Restaurar compras** dentro de StreakRep para recuperar un acceso adquirido con el mismo Apple ID. El acceso Pro depende de la validación de la transacción por Apple y de la disponibilidad temporal de los servicios necesarios.",
    "Si una compra aparece como pendiente, rechazada, reembolsada o no verificable, algunas funciones Pro pueden permanecer bloqueadas hasta que Apple resuelva el estado.",
    "## 7. Reembolsos",
    "Las solicitudes de reembolso se tramitan con Apple mediante reportaproblem.apple.com o el soporte de Apple. StreakRep no puede emitir directamente reembolsos de compras procesadas por Apple.",
    "## 8. Fin de la suscripción",
    "Al finalizar el periodo pagado, perderás el acceso a las funciones Pro y conservarás las funciones gratuitas disponibles en ese momento. Los datos locales y las exportaciones que hayas creado no se eliminan automáticamente por cancelar, salvo que solicites su eliminación o una obligación legal exija otra cosa.",
    "## 9. Información importante",
    "Pro no convierte StreakRep en un producto médico ni garantiza resultados físicos. Las recomendaciones y métricas son orientativas y dependen de la información, permisos y sensores disponibles.",
    "Las funciones sociales pueden estar sujetas a disponibilidad, edad mínima, cuenta iCloud, moderación y reglas adicionales de la comunidad.",
    "## 10. Contacto",
    "Soporte: **romerodev.app+streakreps@gmail.com**",
    "Entidad responsable: **RomeroDev**",
    "Dirección: **Calle Madre Juana María Condesa Lluch 6, Valencia**"
  ],
  body_en: [
    "These conditions complement the Terms of Use and the Privacy Policy.",
    "## 1. What is Pro",
    "StreakRep Pro unlocks premium features which may include advanced analytics, configurable progression, sharing cards, advanced Apple Watch features, iCloud operational backups, and other benefits indicated on the purchase screen.",
    "The exact availability may vary by version, country, device, and configuration of the offer displayed by Apple.",
    "## 2. Purchase and payment provider",
    "Subscriptions are offered through Apple In-App Purchase/StoreKit. Apple manages billing, applicable taxes, and the billing relationship. StreakRep does not receive or store your complete card details.",
    "The purchase screen will show the price, duration, renewal, and conditions of any applicable free trial or introductory offer before you confirm.",
    "## 3. Automatic renewal",
    "Unless you cancel, the subscription will renew automatically at the end of the contracted period. The payment will be charged to your Apple ID typically within the 24 hours prior to the end of the current period.",
    "You can cancel or modify the subscription in:",
    "**Settings on iPhone/iPad → your name → Subscriptions → StreakRep**",
    "Canceling the application or deleting it from the device does not cancel the renewal.",
    "## 4. Free trials and offers",
    "If a free trial is offered, any terms, duration, and subsequent price will be shown on the purchase screen. If you do not cancel before it ends, the corresponding paid subscription will begin.",
    "A person may not be eligible for a trial or offer if they have already used it or if Apple determines they do not meet the requirements.",
    "## 5. Price changes",
    "Apple may apply price changes in accordance with its rules and notification processes. If a change requires your consent, Apple will inform you and may request it before renewing.",
    "No price changes are made simply by updating StreakRep. The conditions that apply are those that appear in Apple for your territory and at the time of purchase.",
    "## 6. Restore purchases and access",
    "You can use **Restore Purchases** within StreakRep to recover access acquired with the same Apple ID. Pro access depends on Apple's validation of the transaction and the temporary availability of the necessary services.",
    "If a purchase appears as pending, declined, refunded, or unverifiable, some Pro features may remain locked until Apple resolves the status.",
    "## 7. Refunds",
    "Refund requests are processed with Apple via reportaproblem.apple.com or Apple Support. StreakRep cannot directly issue refunds for purchases processed by Apple.",
    "## 8. End of subscription",
    "Upon ending the paid period, you will lose access to Pro features and retain the free features available at that time. Local data and exports you have created are not automatically deleted upon cancellation, unless you request their deletion or a legal obligation requires otherwise.",
    "## 9. Important information",
    "Pro does not turn StreakRep into a medical product or guarantee physical results. Recommendations and metrics are orientative and depend on the information, permissions, and sensors available.",
    "Social features may be subject to availability, minimum age, iCloud account, moderation, and additional community rules.",
    "## 10. Contact",
    "Support: **romerodev.app+streakreps@gmail.com**",
    "Responsible Entity: **RomeroDev**",
    "Address: **Calle Madre Juana María Condesa Lluch 6, Valencia**"
  ]
};

const shieldPrivacy: LegalPage = {
  title: "Política de privacidad de Shield",
  title_en: "Shield Privacy Policy",
  updatedAt: "2026-07-13",
  body: [
    "## 1. Procesamiento en el dispositivo",
    "Shield procesa en el dispositivo los documentos, imágenes, texto OCR, máscaras y exportaciones. No utiliza publicidad, seguimiento entre aplicaciones ni un backend propio de analítica.",
    "## 2. Almacenamiento y cifrado",
    "Los documentos originales, archivos de trabajo y cachés de renderizado se cifran localmente con claves vinculadas al dispositivo. La Bóveda utiliza una clave separada y requiere la autenticación configurada en el dispositivo.",
    "Los archivos temporales de exportación se protegen y eliminan cuando termina el flujo de compartir o exportar.",
    "## 3. OCR y revisión",
    "El reconocimiento de texto y las sugerencias de datos sensibles se ejecutan en el dispositivo. La detección automática puede omitir información; debes revisar todas las páginas y zonas seleccionadas antes de compartir una copia.",
    "## 4. iCloud y proveedores de Archivos",
    "La sincronización opcional con iCloud guarda únicamente un índice técnico minimizado en la base privada de CloudKit del usuario. El contenido de imágenes y PDF, los títulos introducidos y los resultados OCR permanecen locales.",
    "Los proveedores externos se acceden mediante el selector Archivos de Apple. Shield recibe únicamente el archivo que eliges y no almacena credenciales OAuth del proveedor.",
    "## 5. Diagnósticos",
    "Los diagnósticos de MetricKit se conservan localmente con protección de datos y rotación limitada. Shield no los transmite al desarrollador.",
    "## 6. Eliminación y contacto",
    "Puedes eliminar los documentos y sus archivos locales desde Ajustes. Para consultas de privacidad, escribe a **support@shieldapp.io**."
  ],
  body_en: [
    "## 1. On-device processing",
    "Shield processes documents, images, OCR text, masks, and exports on the device. It does not use advertising, cross-app tracking, or a developer-operated analytics backend.",
    "## 2. Storage and encryption",
    "Original documents, working files, and render caches are encrypted locally with device-bound keys. The Vault uses a separate key and requires the authentication configured on the device.",
    "Temporary export files are protected and removed when the share or export flow ends.",
    "## 3. OCR and review",
    "Text recognition and sensitive-data suggestions run on device. Automatic detection can miss information; you must review every page and selected area before sharing a copy.",
    "## 4. iCloud and Files providers",
    "Optional iCloud synchronization stores only a minimized technical index in the user's private CloudKit database. Image and PDF content, user-entered titles, and OCR results remain local.",
    "External providers are accessed through Apple's Files picker. Shield receives only the file you select and stores no provider OAuth credentials.",
    "## 5. Diagnostics",
    "MetricKit diagnostics are retained locally with data protection and bounded rotation. Shield does not transmit them to the developer.",
    "## 6. Deletion and contact",
    "You can delete documents and their local files from Settings. For privacy questions, email **support@shieldapp.io**."
  ]
};

const shieldTerms: LegalPage = {
  title: "Términos de uso de Shield",
  title_en: "Shield Terms of Use",
  updatedAt: "2026-07-13",
  body: [
    "## 1. Uso de Shield",
    "Shield ayuda a seleccionar, enmascarar y exportar documentos. Debes disponer de autorización para tratar los archivos importados y revisar el resultado antes de compartirlo.",
    "## 2. Alcance de la verificación",
    "La exportación verificada comprueba propiedades técnicas del archivo generado, incluida la ausencia de texto residual recuperable tras el proceso. No garantiza que el OCR haya detectado todos los datos sensibles ni sustituye asesoramiento legal, regulatorio o profesional.",
    "## 3. Uso responsable",
    "No puedes utilizar Shield para fraude, vulnerar derechos de terceros, tratar documentos sin autorización o eludir obligaciones legales.",
    "## 4. Compras Pro",
    "Las funciones digitales Pro utilizan el sistema de compras integradas de Apple. Las condiciones, precios y renovaciones son los mostrados por App Store y las compras elegibles pueden restaurarse desde Shield.",
    "## 5. Disponibilidad y cambios",
    "Podemos corregir, actualizar o modificar funciones para mejorar la seguridad, compatibilidad y calidad. Las protecciones obligatorias de consumo de tu jurisdicción siguen siendo aplicables.",
    "## 6. Contacto",
    "Soporte: **support@shieldapp.io**. Responsable: Lester Romero Bernardo (RomeroDev), Valencia, España."
  ],
  body_en: [
    "## 1. Using Shield",
    "Shield assists users in selecting, masking, and exporting documents. You must have authority to process imported files and review the result before sharing it.",
    "## 2. Scope of verification",
    "Verified export checks technical properties of the generated file, including recoverable residual text after processing. It does not guarantee that OCR detected every sensitive item and does not replace legal, regulatory, or professional advice.",
    "## 3. Responsible use",
    "You may not use Shield for fraud, infringement of third-party rights, unauthorized document processing, or evasion of legal obligations.",
    "## 4. Pro purchases",
    "Pro digital features use Apple's in-app purchase system. Terms, prices, and renewals are those displayed by the App Store, and eligible purchases can be restored in Shield.",
    "## 5. Availability and changes",
    "We may fix, update, or modify features to improve security, compatibility, and quality. Mandatory consumer protections in your jurisdiction remain applicable.",
    "## 6. Contact",
    "Support: **support@shieldapp.io**. Responsible entity: Lester Romero Bernardo (RomeroDev), Valencia, Spain."
  ]
};

const shieldSubscriptions: LegalPage = {
  title: "Condiciones de suscripción de Shield",
  title_en: "Shield Subscription Terms",
  updatedAt: "2026-07-16",
  body: [
    "## 1. Shield Free y Shield Pro",
    "Shield Free permite importar, escanear, aplicar máscaras y exportar copias verificadas sin una marca de agua forzada, con un límite de 10 documentos activos. La exportación segura, el cifrado y la accesibilidad no son funciones bloqueadas por la suscripción.",
    "Shield Pro añade proyectos activos ilimitados, lotes, plantillas semánticas reutilizables, estilos avanzados, controles de imagen, marcas de agua personalizadas y automatizaciones.",
    "## 2. Compra y facturación",
    "Apple procesa las suscripciones y la compra de por vida. Antes de confirmar, App Store muestra el precio final, impuestos, moneda, duración y ofertas disponibles para tu territorio.",
    "## 3. Renovación y prueba",
    "Las suscripciones se renuevan automáticamente salvo cancelación desde Ajustes > tu nombre > Suscripciones. La prueba gratuita del plan anual, cuando esté disponible y seas elegible, se rige por lo mostrado por Apple antes de la compra.",
    "## 4. Restauración, cancelación y reembolsos",
    "Puedes restaurar compras con el mismo Apple ID desde Shield. Eliminar la app no cancela una suscripción. Apple gestiona cancelaciones y reembolsos de los pagos procesados por App Store.",
    "## 5. Contacto",
    "Soporte: **support@shieldapp.io**."
  ],
  body_en: [
    "## 1. Shield Free and Shield Pro",
    "Shield Free supports importing, scanning, masking, and verified exports without a forced watermark, with a limit of 10 active documents. Secure export, encryption, and accessibility are not subscription gates.",
    "Shield Pro adds unlimited active projects, batch processing, reusable semantic templates, advanced styles, image controls, custom watermarks, and automation.",
    "## 2. Purchase and billing",
    "Apple processes subscriptions and the lifetime purchase. Before confirmation, the App Store shows the final price, taxes, currency, duration, and available offers for your territory.",
    "## 3. Renewal and trial",
    "Subscriptions renew automatically unless canceled from Settings > your name > Subscriptions. The annual-plan free trial, when available and you are eligible, is governed by the terms Apple displays before purchase.",
    "## 4. Restoration, cancellation, and refunds",
    "You can restore purchases made with the same Apple ID from Shield. Deleting the app does not cancel a subscription. Apple handles cancellations and refunds for App Store payments.",
    "## 5. Contact",
    "Support: **support@shieldapp.io**."
  ]
};

export function enrichKnownProduct(app: AppItem): AppItem {
  if (app.slug === "shield") return {
    ...app,
    updatedAt: "2026-07-16",
    iconUrl: "assets/images/shield/shield-icon.png",
    coverImageUrl: "assets/images/shield/screens/simulator/01-home_es.jpg",
    screenshots: ["01-home", "02-capture", "03-editor", "04-ocr", "05-export", "07-vault", "08-batch", "10-settings"],
    pricing: [
      { name: "Mensual", name_en: "Monthly", price: "2,99 €", cadence: "/mes", cadence_en: "/month", description: "Acceso flexible a Shield Pro.", description_en: "Flexible access to Shield Pro.", isIndicative: true },
      { name: "Anual", name_en: "Annual", price: "29,99 €", cadence: "/año", cadence_en: "/year", description: "Incluye una prueba gratuita de 7 días para cuentas elegibles.", description_en: "Includes a 7-day free trial for eligible accounts.", badge: "Mejor valor", badge_en: "Best value", featured: true, isIndicative: true },
      { name: "De por vida", name_en: "Lifetime", price: "49,99 €", cadence: "pago único", cadence_en: "one-time", description: "Acceso permanente a Shield Pro.", description_en: "Permanent access to Shield Pro.", isIndicative: true }
    ],
    freeFeatures: [
      "Importación, cámara y escáner",
      "Máscaras manuales y sugerencias OCR",
      "Exportación rasterizada y verificada",
      "Cifrado local y Bóveda protegida",
      "Hasta 10 documentos activos"
    ],
    freeFeatures_en: [
      "Importing, camera, and scanner",
      "Manual masks and OCR suggestions",
      "Rasterized, verified export",
      "Local encryption and protected Vault",
      "Up to 10 active documents"
    ],
    proFeatures: [
      "Proyectos activos ilimitados",
      "Procesamiento por lotes",
      "Plantillas semánticas reutilizables",
      "Estilos y controles de imagen avanzados",
      "Marcas de agua y automatizaciones"
    ],
    proFeatures_en: [
      "Unlimited active projects",
      "Batch processing",
      "Reusable semantic templates",
      "Advanced styles and image controls",
      "Custom watermarks and automation"
    ],
    faq: [
      { question: "¿Shield sube mis documentos a un servidor?", question_en: "Does Shield upload my documents to a server?", answer: "No. Los documentos, imágenes, OCR, máscaras y exportaciones se procesan en el dispositivo. La sincronización opcional con iCloud guarda solo un índice técnico minimizado en tu base privada de CloudKit; el contenido y los resultados OCR permanecen locales.", answer_en: "No. Documents, images, OCR, masks, and exports are processed on device. Optional iCloud sync stores only a minimized technical index in your private CloudKit database; content and OCR results remain local." },
      { question: "¿Qué significa exportación verificada?", question_en: "What does verified export mean?", answer: "Shield rasteriza la copia y comprueba propiedades técnicas del resultado, incluido el texto residual recuperable. La verificación no puede saber si olvidaste seleccionar un dato sensible, por lo que siempre debes revisar todas las páginas.", answer_en: "Shield flattens the copy and checks technical properties of the output, including recoverable residual text. Verification cannot know whether you forgot to select sensitive data, so every page still requires review." },
      { question: "¿El OCR oculta todos los datos automáticamente?", question_en: "Does OCR hide every sensitive item automatically?", answer: "No. El OCR ofrece sugerencias conservadoras para ayudarte a localizar campos, pero puede cometer errores u omisiones. Tú decides qué zonas se ocultan y confirmas el resultado antes de exportar.", answer_en: "No. OCR offers conservative suggestions to help locate fields, but it can make mistakes or omissions. You decide which areas are hidden and confirm the result before export." },
      { question: "¿Qué puedo importar?", question_en: "What can I import?", answer: "Puedes usar cámara, escáner de documentos, Fotos, Archivos, PDF y la extensión Compartir. Los proveedores externos disponibles en Archivos aparecen mediante el selector nativo de Apple.", answer_en: "You can use the camera, document scanner, Photos, Files, PDF, and the Share Extension. External providers available in Files appear through Apple's native picker." },
      { question: "¿Qué incluye Shield Free?", question_en: "What is included in Shield Free?", answer: "Hasta 10 documentos activos, captura e importación, máscaras manuales, sugerencias OCR, almacenamiento cifrado y exportación verificada sin marca de agua forzada. Las funciones de seguridad esenciales no son exclusivas de Pro.", answer_en: "Up to 10 active documents, capture and import, manual masks, OCR suggestions, encrypted storage, and verified export without a forced watermark. Essential safety features are not exclusive to Pro." },
      { question: "¿Funciona en iPad y con tecnologías de accesibilidad?", question_en: "Does it work on iPad and with accessibility technologies?", answer: "Sí. Shield es una app universal para iPhone y iPad, con soporte para teclado, VoiceOver y Dynamic Type.", answer_en: "Yes. Shield is a universal iPhone and iPad app with keyboard, VoiceOver, and Dynamic Type support." }
    ],
    legal: { privacy: shieldPrivacy, terms: shieldTerms, subscriptions: shieldSubscriptions }
  };

  if (app.slug === "reps") return {
    ...app,
    name: "StreakRep",
    updatedAt: "2026-07-16",
    tagline: "Entrena con un plan. Progresa con datos.",
    tagline_en: "Workout tracking for consistent strength progress.",
    shortDescription: "Planifica rutinas, registra cada serie desde iPhone o Apple Watch y entiende fuerza, recuperación, volumen y constancia.",
    shortDescription_en: "Plan workouts, log every set from iPhone or Apple Watch and understand strength, recovery, volume and consistency.",
    longDescription: "StreakRep convierte tu entrenamiento en un sistema claro: planes estructurados, registro rápido, progresión, recuperación, rutas GPS y análisis de fuerza conectados con el ecosistema Apple.",
    longDescription_en: "StreakRep turns training into a clear system: structured plans, fast logging, progression, recovery, GPS routes and strength analytics connected to the Apple ecosystem.",
    seo: {
      title: "StreakRep - Entrenamiento de fuerza, progreso y recuperación | RomeroDev",
      description: "StreakRep para iPhone y Apple Watch: planes, registro de series, fuerza, recuperación, rutas GPS y Apple Health."
    },
    iconUrl: "assets/images/reps/icons/reps-icon.png",
    coverImageUrl: "assets/images/reps/screens/simulator/01-today-readiness_es.jpg",
    screenshots: ["01-today-readiness", "02-progress-summary", "03-progress-weekly-bars", "05-train-plan", "06-exercises-muscle-map", "07-exercises-core-filter", "08-progress-health-bars", "09-workout-detail-muscles"],
    benefits: [
      "Entrena sin perder el foco: Registra peso, repeticiones, RPE y descansos desde una sola vista.",
      "Decide con contexto: Combina carga, sueño, HRV, pulso y recuperación.",
      "Demuestra el progreso: Sigue récords, 1RM, volumen, rachas y equilibrio muscular.",
      "Todo el ecosistema Apple: HealthKit, Apple Watch, widgets, Live Activities, Siri y App Intents."
    ],
    benefits_en: [
      "Stay focused: Log weight, reps, RPE and rest from one workout view.",
      "Decide with context: Bring load, sleep, HRV, resting heart rate and recovery together.",
      "Prove progress: Follow PRs, estimated 1RM, volume, streaks and muscle balance.",
      "Built for Apple: HealthKit, Apple Watch, widgets, Live Activities, Siri and App Intents."
    ],
    features: [
      "Planes y programas: Fuerza, hipertrofia, full body y push-pull-legs con progresión configurable.",
      "Registro avanzado: Series, peso, repeticiones, RPE, calentamientos, notas y descanso.",
      "Analítica de fuerza: Récords, 1RM estimado, volumen semanal, tendencias y mapa muscular.",
      "Recuperación: Sueño, HRV, pulso en reposo, carga y recomendaciones orientativas.",
      "Entrenamiento exterior: Ruta GPS, ritmo, distancia, desnivel, frecuencia cardiaca y parciales.",
      "Apple Watch: Consulta el plan y registra series desde la muñeca.",
      "Privacidad y control: Exportación JSON/CSV y backup operativo en iCloud."
    ],
    features_en: [
      "Plans and programs: Strength, hypertrophy, full body and push-pull-legs with configurable progression.",
      "Advanced logging: Sets, weight, reps, RPE, warm-ups, notes and rest timers.",
      "Strength analytics: PRs, estimated 1RM, weekly volume, trends and a visual muscle map.",
      "Recovery context: Sleep, HRV, resting heart rate, training load and orientative recommendations.",
      "Outdoor training: GPS route, pace, distance, elevation, heart rate and splits.",
      "Apple Watch: Follow the plan and log sets from your wrist.",
      "Privacy and control: JSON export and operational iCloud backups."
    ],
    pricing: [
      { name: "Semanal", name_en: "Weekly", price: "0,99 €", cadence: "/semana", cadence_en: "/week", description: "Acceso Pro flexible.", description_en: "Flexible Pro access.", isIndicative: true },
      { name: "Mensual", name_en: "Monthly", price: "1,99 €", cadence: "/mes", cadence_en: "/month", description: "Cancela cuando quieras.", description_en: "Cancel whenever you want.", badge: "Flexible", isIndicative: true },
      { name: "Anual", name_en: "Annual", price: "8,99 €", cadence: "/año", cadence_en: "/year", description: "La opción prevista con mejor relación de valor.", description_en: "The planned best-value option.", badge: "Mejor valor", badge_en: "Best value", featured: true, isIndicative: true },
      { name: "Vitalicio", name_en: "Lifetime", price: "19,99 €", cadence: "pago único", cadence_en: "one-time", description: "Acceso permanente a StreakRep Pro.", description_en: "Permanent StreakRep Pro access.", isIndicative: true }
    ],
    freeFeatures: ["Registro ilimitado", "Biblioteca de ejercicios", "Rutinas personalizadas", "Analítica básica"],
    freeFeatures_en: ["Unlimited logging", "Exercise library", "Custom routines", "Basic analytics"],
    proFeatures: ["Analítica avanzada", "Progresión configurable", "Backups automáticos", "Tarjetas para compartir", "Integración avanzada con Apple Watch"],
    proFeatures_en: ["Advanced analytics", "Configurable progression", "Automatic backups", "Share cards", "Advanced Apple Watch integration"],
    faq: [
      { question: "¿StreakRep sustituye a un entrenador o profesional sanitario?", question_en: "Does StreakRep replace a coach or healthcare professional?", answer: "No. StreakRep organiza y analiza entrenamientos; sus métricas y sugerencias son orientativas y no constituyen consejo médico.", answer_en: "No. StreakRep organizes and analyzes workouts; its metrics and suggestions are informational and do not constitute medical advice." },
      { question: "¿Puedo usar StreakRep sin Apple Watch?", question_en: "Can I use StreakRep without an Apple Watch?", answer: "Sí. La experiencia completa de planificación, registro y progreso funciona en iPhone. Apple Watch añade registro desde la muñeca y continuidad durante la sesión.", answer_en: "Yes. Planning, workout logging and progress tracking all work on iPhone. Apple Watch adds wrist-based logging and continuity during a session." },
      { question: "¿Qué datos lee de Apple Health?", question_en: "What data does StreakRep read from Apple Health?", answer: "Solo las categorías que autorices, como entrenamientos, actividad, métricas corporales y señales de recuperación. Puedes revocar el permiso en cualquier momento.", answer_en: "Only categories you authorize, such as workouts, activity, body metrics and recovery signals. You can revoke access at any time." },
      { question: "¿Los precios ya son definitivos?", question_en: "Are these prices final?", answer: "No mientras StreakRep no esté publicado. La tabla muestra la configuración prevista del proyecto; App Store mostrará siempre el precio contractual final para cada territorio.", answer_en: "Not until StreakRep is released. The table reflects the planned configuration; the App Store will always show the final contractual price for your territory." },
      { question: "¿Cómo cancelo StreakRep Pro?", question_en: "How do I cancel StreakRep Pro?", answer: "Desde Ajustes del iPhone o iPad, pulsa tu nombre y entra en Suscripciones. Eliminar la app no cancela una suscripción activa.", answer_en: "Open Settings on iPhone or iPad, tap your name and choose Subscriptions. Deleting the app does not cancel an active subscription." },
      { question: "¿Puedo exportar mis entrenamientos?", question_en: "Can I export my workouts?", answer: "Sí. StreakRep contempla exportación JSON para que mantengas control sobre tu historial.", answer_en: "Yes. StreakRep supports JSON export so you keep control of your workout history." }
    ],
    legal: { privacy: repsPrivacy, terms: repsTerms, subscriptions: repsSubscriptions }
  };

  if (app.slug === "vitalspath") return {
    ...app,
    coverImageUrl: "assets/images/vitalspath/screen-01-dashboard.PNG",
    pricing: [
      { name: "Mensual", name_en: "Monthly", price: "4,99 €", cadence: "/mes", cadence_en: "/month", description: "Acceso Premium con renovación mensual.", description_en: "Premium access billed monthly." },
      { name: "Anual", name_en: "Annual", price: "39,99 €", cadence: "/año", cadence_en: "/year", description: "Premium para el cuidado continuado.", description_en: "Premium for ongoing family care.", badge: "Más popular", badge_en: "Most popular", featured: true },
      { name: "Vitalicio", name_en: "Lifetime", price: "149,99 €", cadence: "pago único", cadence_en: "one-time", description: "Premium permanente, sin renovación.", description_en: "Permanent Premium access without renewal." }
    ],
    freeFeatures: ["Registro de medicación", "Síntomas y constantes", "Citas y recordatorios", "Perfil personal"],
    freeFeatures_en: ["Medication logging", "Symptoms and vitals", "Appointments and reminders", "Personal profile"],
    proFeatures: ["Perfiles familiares", "Cuidados compartidos", "Informes avanzados", "Sincronización iCloud", "Apple Watch, widgets y Live Activities"],
    proFeatures_en: ["Family profiles", "Shared care", "Advanced reports", "iCloud sync", "Apple Watch, widgets and Live Activities"],
    faq: [
      ...app.faq,
      { question: "¿Cómo se gestionan las compras Premium?", answer: "Apple procesa el pago y la renovación. Puedes restaurar compras con el mismo Apple ID y gestionar o cancelar la suscripción desde Ajustes > tu nombre > Suscripciones." },
      { question: "¿Puedo exportar información para una consulta?", answer: "Sí. VitalsPath puede preparar informes para facilitar la conversación con profesionales sanitarios; la app no interpreta esos informes como diagnóstico." }
    ],
    legal: {
      privacy: {
        title: "Política de privacidad de VitalsPath",
        updatedAt: "2026-07-11",
        body: [
          "## 1. Responsable", `Responsable: Lester Romero Bernardo (RomeroDev), Valencia, España. Contacto de privacidad: ${app.supportEmail}.`,
          "## 2. Datos y finalidad", "VitalsPath puede tratar perfiles, medicación, síntomas, constantes, citas, notas de cuidado, estado de compras, ubicación aproximada y diagnósticos técnicos para organizar el cuidado, sincronizar dispositivos, validar Premium y mantener la estabilidad.",
          "## 3. Salud y permisos", "Los permisos de HealthKit, notificaciones, cámara y otros servicios son opcionales y se solicitan cuando una función los necesita. VitalsPath no vende datos de salud ni los utiliza para publicidad.",
          "## 4. Almacenamiento y proveedores", "Los datos pueden almacenarse localmente y sincronizarse mediante servicios de Apple/iCloud según las funciones activadas. Apple procesa compras; servicios de diagnóstico pueden recibir información técnica y de uso conforme a sus políticas.",
          "## 5. Cuidados compartidos", "Cuando compartes un perfil con familiares o cuidadores, las personas invitadas podrán acceder al contenido autorizado. Revisa siempre a quién concedes acceso y retíralo cuando deje de ser necesario.",
          "## 6. Conservación y derechos", "Puedes corregir o eliminar registros desde la app y solicitar acceso, rectificación, supresión, limitación, oposición o portabilidad por email. También puedes reclamar ante la AEPD.",
          "## 7. Seguridad y menores", "Aplicamos minimización y controles razonables. Protege tu dispositivo y Apple ID. VitalsPath no está destinada a que menores gestionen datos de salud sin supervisión adecuada.",
          "## 8. Contacto", `Consultas y solicitudes: ${app.supportEmail}. Los cambios se publicarán aquí con su fecha de actualización.`
        ]
      },
      terms: {
        title: "Términos de uso de VitalsPath",
        updatedAt: "2026-07-11",
        body: [
          "## 1. Aceptación", "Al utilizar VitalsPath aceptas estos términos y su política de privacidad.",
          "## 2. Naturaleza del servicio", "VitalsPath es una herramienta organizativa. No es un dispositivo médico, no diagnostica, prescribe ni sustituye a profesionales. En una emergencia contacta con los servicios sanitarios.",
          "## 3. Uso responsable", "Debes revisar recordatorios, dosis y datos introducidos. No utilices la app para fines ilegales, acceso no autorizado, suplantación o gestión de datos de terceros sin permiso.",
          "## 4. Cuenta, permisos y sincronización", "Eres responsable de proteger tu dispositivo y Apple ID. HealthKit, iCloud, notificaciones y Apple Watch dependen de permisos y servicios de Apple y pueden sufrir interrupciones.",
          "## 5. Propiedad intelectual", "La app, marca, diseño y materiales pertenecen a Lester Romero Bernardo / RomeroDev o a sus licenciantes. Se concede una licencia personal, limitada y no transferible.",
          "## 6. Compras", "Las compras se procesan por Apple y se someten a las condiciones de suscripción publicadas en esta web y a la información mostrada antes de pagar.",
          "## 7. Disponibilidad y responsabilidad", "Podemos actualizar funciones. Las métricas y alertas son auxiliares y no garantizamos disponibilidad ininterrumpida. No se limitan derechos irrenunciables del consumidor.",
          "## 8. Legislación y contacto", `Se aplica la legislación española y europea de consumo. Soporte: ${app.supportEmail}.`
        ]
      },
      subscriptions: subscriptionTerms("VitalsPath", app.supportEmail, "2026-07-11")
    }
  };
  return app;
}
